name: Auto Formattter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  auto_format:
    name : apply clang-formatting
    runs-on: ubuntu-latest

    steps:
      - name : Install formatting deps
        run: |
          sudo apt update
          sudo apt -y install clang-format-14
          clang-format-14 --version

      - name : Checkout code
        uses : actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name : Run Formatting
        shell : bash
        run : find apps audioDevice dsp synthtools utilities -iname *.h -o -iname *.hpp -o -iname *.cpp | xargs clang-format-14 -style=file -verbose -i

      - name : Commit & push changes
        uses : actions-js/push@master
        with :
          message: "Auto formatting applied"
          branch : ${{ github.head_ref }}
          github_token : ${{ secrets.GITHUB_TOKEN }}
