name: Build and Test

on:
  push:
    branches: [ "feature/cmake_presets" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04 
    strategy:
      matrix:
        compiler : [gcc, clang]
        configuration : [debug, release]

    steps:
    - name : install ninja build 
      run  : sudo apt-get install -y ninja-build

    - name : install alsa 
      run  : sudo apt-get install -y libasound2-dev

    - name : install lcov
      run  : sudo apt-get install -y lcov

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake --preset=${{matrix.compiler}}-${{matrix.configuration}}

    - name: Build
      run: cmake --build --preset=${{matrix.compiler}}-${{matrix.configuration}} 

    - name : Run tests
      run : GTEST_COLOR=1 ctest --preset=${{matrix.compiler}}-${{matrix.configuration}} --verbose


    - name: Generate a code coverage report
      uses: threeal/gcovr-action@v1.0.0
      with:
      excludes: |
        '*/*Test*'
        '*deps/*'

    ## https://gcovr.com/en/stable/guide/compiling.html?      
    # - name : Create coverage report
    #   run : |
    #         lcov --directory ${{github.workspace}}/build/gcc-release --capture --output=${{github.workspace}}/build/gcc-release/lcov.info
    #         lcov --remove ${{github.workspace}}/build/gcc-release/lcov.info '*deps/*' '/usr/include/*' '*/*Test*' --output-file ${{github.workspace}}/build/gcc-release/lcov.info
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file:  ${{github.workspace}}/build/gcc-release/lcov.info
